#!/bin/zsh

# don't continue if not interactive
[[ $- != *i* ]] && return

# STOP FUCKING BEEPING!
unsetopt BEEP
setopt NOBEEP

# zsh specific aliases
alias mpv="noglob mpv"

# brew
[ -f "/opt/homebrew/bin/brew" ] && eval "$(/opt/homebrew/bin/brew shellenv zsh)"
export HOMEBREW_NO_ENV_HINTS=1
PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

# better history
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS

setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS

setopt INC_APPEND_HISTORY_TIME
setopt SHARE_HISTORY
HISTFILE="$XDG_DATA_HOME/zsh-history"

# enable completion
autoload -Uz compinit && compinit
unsetopt AUTO_REMOVE_SLASH
zstyle ':completion:*' verbose no
bindkey '^[[Z' reverse-menu-complete

# oksh/fish like C-w
export WORDCHARS='_-'

# fish like history substring search
autoload -Uz up-line-or-beginning-search
autoload -Uz down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

__exit_status() {
    EXIT_STATUS="$?"
    if [ "$EXIT_STATUS" != 0 ] && [ "$EXIT_STATUS" != 130 ]; then
        printf "\e[0;31m%s\e[0m\n" "[exit status: $EXIT_STATUS]"
    fi
    unset EXIT_STATUS
}

__set_title() {
    printf '\033]0;%s %s\033\\' "$HOSTNAME" "${PWD/#$HOME/~}"
}

__set_current_prompt_pwd() {
    __CURRENT_PROMPT_PWD="${PWD/#$HOME/~}"
    [ -f "$(command -v fishy-pwd)" ] && __CURRENT_PROMPT_PWD="$(fishy-pwd)"
}

precmd() {
    __exit_status
    __set_title
    __set_current_prompt_pwd
    PROMPT="%f%m %F{014}${__CURRENT_PROMPT_PWD}%f \$ "
}
