#!/bin/zsh

# don't continue if not interactive
[[ $- != *i* ]] && return

# STOP FUCKING BEEPING!
unsetopt BEEP

# brew
[ -f "/opt/homebrew/bin/brew" ] && eval "$(/opt/homebrew/bin/brew shellenv zsh)"

# better history
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS

setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS

setopt INC_APPEND_HISTORY_TIME
setopt SHARE_HISTORY
HISTFILE="$XDG_DATA_HOME/zsh-history"

# enable completion
autoload -Uz compinit && compinit
unsetopt AUTO_REMOVE_SLASH
zstyle ':completion:*' verbose no
bindkey '^[[Z' reverse-menu-complete

# oksh/fish like C-w
export WORDCHARS=${WORDCHARS//\//}

# fish like history substring search
autoload -Uz up-line-or-beginning-search
autoload -Uz down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

__exit_status() {
    EXIT_STATUS="$?"
    if [ "$EXIT_STATUS" != 0 ] && [ "$EXIT_STATUS" != 130 ]; then
        printf "\e[0;31m%s\e[0m\n" "[exit status: $EXIT_STATUS]"
    fi
    unset EXIT_STATUS
}

__update_title() {
    printf '\033]0;%s %s' "$HOSTNAME" "${PWD/#$HOME/~}"
}

PROMPT="%f%m %F{014}%~%f \$ "

precmd() {
    __exit_status
    __update_title
    [ -f "$(command -v fishy-pwd)" ] && PROMPT="%f%m%f %F{014}$(fishy-pwd)%f \$ "
}
