COMMON_FLAGS="-march=native -mtune=native -O2 -pipe -frecord-gcc-switches"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

LDFLAGS="${LDFLAGS} -Wl,--defsym=__gentoo_check_ldflags__=0"

PORTAGE_ELOG_CLASSES="log warn error qa"
PORTAGE_ELOG_SYSTEM="echo save"

# gentoo requires this if you report bugs
LC_MESSAGES="C.utf8"

MAKEOPTS="-j8 -l8"

ACCEPT_LICENSE="-* @FREE"

# VIDEO and DEVICES
INPUT_DEVICES="libinput wacom"
VIDEO_CARDS="intel"

# ENGLISH
L10N="en en_AU en_GB en-AU en-GB"

# use https mirrors
GENTOO_MIRRORS="
    https://ftp.swin.edu.au/gentoo
    https://mirror.aarnet.edu.au/pub/gentoo/
    https://mirror.rackspace.com/gentoo/
    https://distfiles.gentoo.org
"

FEATURES="collision-protect ipc-sandbox network-sandbox sandbox split-elog split-log strict suidctl test-fail-continue userfetch userpriv usersandbox"

USE="bluetooth dbus elogind icu opengl pipewire pulseaudio udev vaapi vulkan wayland -X -initramfs -ipv6 -suid -vala"
