COMMON_FLAGS="-march=native -mtune=native -O2 -pipe -frecord-gcc-switches"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

LDFLAGS="${LDFLAGS} -Wl,--defsym=__gentoo_check_ldflags__=0"

PORTAGE_ELOG_CLASSES="log warn error qa"
PORTAGE_ELOG_SYSTEM="echo save"

# gentoo requires this if you report bugs
LC_MESSAGES="C.utf8"

MAKEOPTS="-j24 -l24"

ACCEPT_LICENSE="-* @FREE"

# DEVICES
INPUT_DEVICES="libinput wacom"

# use https mirrors
GENTOO_MIRRORS="
    https://ftp.swin.edu.au/gentoo
    https://mirror.aarnet.edu.au/pub/gentoo/
    https://mirror.rackspace.com/gentoo/
    https://distfiles.gentoo.org
"

FEATURES="collision-protect ipc-sandbox network-sandbox sandbox split-elog split-log strict suidctl test-fail-continue userfetch userpriv usersandbox"

USE="bluetooth dbus elogind icu opengl pipewire pulseaudio udev vaapi vulkan wayland -initramfs -ipv6 -suid -systemd -vala"
