cache=auto
embeddedfonts=no
hwdec=auto
script-opts=ytdl_hook-ytdl_path=yt-dlp
slang=eng,en,enUS
ytdl-format=[format_id*=adaptive_hls-audio-jaJP][height<=?1080][fps<=?30]/bestvideo[height<=?1080][fps<=?30]+bestaudio/best
