#!/bin/sh

if [ -x /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv sh)"
    [ -d /opt/homebrew/opt/gnu-sed/libexec/gnubin ] && PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
    [ -d /opt/homebrew/opt/coreutils/libexec/gnubin ] && PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
fi
export HOMEBREW_NO_ENV_HINTS=1
