colorscheme ziglang.org

# create directory before writing
hook -group user-bufwritepre global BufWritePre .* %{
    nop %sh{ mkdir -p "$(dirname "${kak_hook_param}")" }
}

# I used this all the time in vim/neovim/helix
alias global x write-quit

# keybinds
map global user j ':tmux-repl-horizontal<ret>' -docstring 'open tmux pane'
map global user c ':comment-line<ret>' -docstring 'toggle comment'

map global goto n '<esc>:bn<ret>' -docstring 'next buffer'
map global goto p '<esc>:bp<ret>' -docstring 'previous buffer'

add-highlighter global/ number-lines -hlcursor -separator " " -min-digits 3
add-highlighter global/ regex '\b(FIXME|IMPORTANT|NOTE|TODO|WARNING|XXX)\b:' 0:default+rb
add-highlighter global/ regex '\h+$' 0:default,rgb:ee3333
add-highlighter global/ show-matching

# default wrap
set-option global autowrap_column 72

# simpler assistant
set-option global ui_options terminal_assistant=none

# four is the lucky number
set-option global tabstop 4
set-option global indentwidth 4
add-highlighter global/yikes-thems-tabs show-whitespaces -spc ' ' -lf ' '

# spaces please
hook -group expandtabs global InsertChar \t %{ exec -draft h@ }
# except in these files
hook global BufCreate (.*\.(ebuild|c|h)$)|.*/metadata.xml|.*Makefile %{
    set-option buffer disabled_hooks expandtabs
}

# respect editorconfig
hook global BufCreate .* %{ try editorconfig-load }


# filetypes
hook global BufCreate (/etc/portage/(m|p).*|.*tmux\.conf) %{
    set-option buffer filetype sh
}

hook global BufCreate /etc/portage/repos.conf/.* %{
    set-option buffer filetype ini
}

hook global BufCreate .* %{ try modeline-parse }
