colorscheme modus-vivendi

# create directory before writing
hook -group user-bufwritepre global BufWritePre .* %{
    nop %sh{ mkdir -p "$(dirname "${kak_hook_param}")" }
}

# I used this all the time in vim/neovim/helix
alias global x write-quit

# keybinds
map global normal ' ' ''
map global normal \; ':enter-user-mode user<ret>' -docstring 'enter <user> user mode'
map global user \; ':comment-line<ret>' -docstring 'toggle comment'
map global user j ':tmux-repl-horizontal<ret>' -docstring 'open tmux pane'
map global user k ':lsp-hover<ret>' -docstring 'show info for current position'
map global user l ':enter-user-mode lsp<ret>' -docstring 'enter lsp user mode'

# clipboard
map global user p '!wl-paste -n<ret>' -docstring 'paste from clipboard'
map global user y '<a-|>wl-copy<ret>' -docstring 'yank to clipboard'

# wrap
map global user w '|fold -sw 72<ret>' -docstring 'wrap to 72'
map global user W '|fold -sw 80<ret>' -docstring 'wrap to 80'

map global goto n '<esc>:bn<ret>' -docstring 'next buffer'
map global goto p '<esc>:bp<ret>' -docstring 'previous buffer'

# extra highlighters
add-highlighter global/ number-lines -hlcursor -separator " " -min-digits 3
add-highlighter global/ regex '\b(FIXME|IMPORTANT|NOTE|TODO|WARNING|XXX)\b:' 0:default+rb
add-highlighter global/ regex '\h+$' 0:default,red
add-highlighter global/ show-matching

hook global WinSetOption filetype=python %{
    add-highlighter shared/python/code/extra-operator regex '(<|>|=|:=|-)' 1:operator
    add-highlighter shared/python/code/global regex '\b([A-Z_]+)\b' 1:variable
    add-highlighter shared/python/code/variable regex '\.\b(\w+)\b' 1:variable
    add-highlighter shared/python/code/function regex '\b(\w+)\(' 1:function
}

hook global WinSetOption filetype=zig %{add-highlighter shared/zig/code/function regex '\b(\w+)\(' 1:function}
hook global WinSetOption filetype=c %{add-highlighter shared/c/code/function regex '\b(\w+)\(' 1:function}
hook global WinSetOption filetype=cpp %{add-highlighter shared/cpp/code/function regex '\b(\w+)\(' 1:function}

hook global BufCreate (/etc/portage/((m|p).*|sets/.*)|/var/lib/portage/.*) %{
    add-highlighter buffer/ regex '^(<=|>=|<|>|)\b([a-z].*?)/(.*?)\b( |\n)' 2:type 3:keyword
    add-highlighter buffer/ regex " ([\w-]+)" 1:green
    add-highlighter buffer/ regex " (-[\w'-]+)" 1:red
}

# default wrap
set-option global autowrap_column 72

# simpler assistant
set-option global ui_options terminal_assistant=none

# four is the lucky number
set-option global tabstop 4
set-option global indentwidth 4
add-highlighter global/yikes-thems-tabs show-whitespaces -spc ' ' -lf ' '

# spaces please
hook -group expandtabs global InsertChar \t %{ exec -draft h@ }
# except in these files
hook global BufCreate (.*\.(ebuild|c|h)$)|.*/metadata.xml|.*Makefile %{
    set-option buffer disabled_hooks expandtabs
}

# respect editorconfig
hook global BufCreate .* %{ try editorconfig-load }

# lsp
try %{
    eval %sh{kak-lsp --kakoune -s $kak_session}
    lsp-enable
    lsp-inlay-diagnostics-enable global # requires kakoune 2024 or newer
}

# formatting
define-command -hidden format-on-save %{
    hook -group format-on-save window BufWritePre .* format
    hook -once -always WinSetOption filetype=.* %{
        unset-option window formatcmd
        remove-hooks window format-on-save
    }
}

hook global WinSetOption filetype=python %{
    set-option window formatcmd "black --quiet -"
    format-on-save
}
hook global WinSetOption filetype=rust %{
    set-option window formatcmd rustfmt
    format-on-save
}

# filetypes
hook global BufCreate (/etc/portage/((m|p).*|sets/.*)|/var/lib/portage/.*|.*tmux\.conf) %{
    set-option buffer filetype sh
}

hook global BufCreate /etc/portage/repos.conf/.* %{
    set-option buffer filetype ini
}

hook global BufCreate .* %{ try modeline-parse }
