# set the white balance
redshift -O 4800 &

# "xmodmap is deprecated" <-- tell me that when setxkbmap has feature parity.
xmodmap "$XDG_CONFIG_HOME/x11/xmodmap"
xrdb "$XDG_CONFIG_HOME/x11/xresources"

# real smooth scrolling in FF
export MOZ_USE_XINPUT2=1

# XDG_*_DIRs
export XDG_DESKTOP_DIR="$HOME/dev"
export XDG_DOCUMENTS_DIR="$HOME/dev"
export XDG_DOWNLOAD_DIR="$HOME/downloads"
export XDG_MUSIC_DIR="$HOME/music"
export XDG_VIDEOS_DIR="$HOME/videos"

# imput method
export XMODIFIERS=@im=exwm-xim
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
export CLUTTER_IM_MODULE=xim

# now start exwm! :)
exec emacs --no-site-lisp
