brew "bash-completion@2"
brew "bash"
brew "black"
brew "coreutils"
brew "git"
brew "gnu-sed"
brew "gnupg"
brew "grep"
brew "kakoune"
brew "llama.cpp"
brew "man-db"
brew "mole" if OS.mac?
brew "mpv"
brew "opencode"
brew "prettier"
brew "ripgrep"
brew "ruff"
brew "rustup"
brew "screen"
brew "shellcheck"
brew "shfmt"
brew "stylua"
brew "uv"

cask "firefox" if OS.mac?
cask "font-jetbrains-mono" if OS.mac?
cask "ghostty" if OS.mac?
cask "mozilla-vpn" if OS.mac?

uv "llm", with: ["llm-openrouter", "llm-tools-exa"]
uv "l2l", source: "git+https://github.com/cjbayliss/l2l.git"
