#!/bin/sh

printf 'Are you sure you want to run gentoo-world-check? IT CAN TAKE SOME TIME!! (y/N)? '
read -r answer

if [ "$answer" != "${answer#[Yy]}" ]; then
    rm -i /tmp/deselect
    while read -r i ; do
        if [ -n "$(qdepends -Q $i)" ]; then
            printf "\nchecking %s\n" "$i"
            if [ -n "$(emerge -p --quiet --depclean $i)" ]; then
                echo "$i needs to stay in @world"
            else
                echo "$i can be deselected"
                echo "$i" >> /tmp/deselect
            fi
        fi
    done < /var/lib/portage/world
    printf "\n/tmp/deselect contains candidates for deselection\n"
    printf "try: emerge --ask --deselect \$(< /tmp/deselect)\n"
fi
