#!/bin/bash

######################################################
###                                                ###
###   THIS IS UGLY, LIKE MOST OF MY BASH SCRIPTS   ###
###                                                ###
######################################################

# get-img, a script to get a direct link to the image from various
# sites. Currently tested sites are imgur.com, t.co, and ibb.co
#
# NOTE: you may get a url with '?fb' or ':large' on the end, you can
# remove that part when you copy it

# We create a tmp name, this is so we can refer to the file later
tmp_name=$(date --rfc-3339=seconds | shasum | cut -d' ' -f1)

# We'll store a copy of the html in ~/.cache, then delete it (this is
# bad, needless write to drive a BAD!!)
cache='.cache/get-img'
mkdir -p ~/"$cache"
wget -c "$1" -O ~/"$cache"/"$tmp_name" -o ~/"$cache"/get-img.log

# now the easy part, get the image url
grep 'og:image"' ~/"$cache"/"$tmp_name" | cut -d'"' -f4

# finally, delete the downloaded html
rm ~/"$cache"/"$tmp_name"
