#!/bin/bash

name=$1
upstream=${2:-origin}

if [[ -z $name ]]
then
  echo "Branch name invalid."
  echo "usage: ${0##*/} branch [remote]"
  exit 1
fi

git checkout -b "$name" "$upstream"/staging &&
git push "$upstream" "$name" &&
git branch --set-upstream "$name" "$upstream"/"$name"
