#!/bin/bash

# This script is designed to show which branches you have locally that
# aren't being tracked by the specified upstream remote. It may take a
# while to go through these branches depending on how many there are.

upstream="${1:-origin}"
while read -r branch
do
  git branch -a --contains "$branch" | grep -q ^..remotes/"$upstream" \
    || echo "$branch"
done < <(git branch -a | sed -n "s/^..//;/ -> /d;/^remotes\/$upstream/"'!p')
