#!/bin/sh
# real smooth scrolling in FF
# FIXME: is this needed under sway?
export MOZ_USE_XINPUT2=1

# ibus input stuff
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus 

# set QT theme engine. requires qt5ct -_-
export QT_QPA_PLATFORMTHEME="qt5ct"

# wayland stuff
export QT_QPA_PLATFORM=wayland
export GDK_BACKEND=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION="1"

# XDG_*_DIRs
export XDG_DESKTOP_DIR="$HOME/dev"
export XDG_DOCUMENTS_DIR="$HOME/dev"
export XDG_DOWNLOAD_DIR="$HOME/downloads"
export XDG_MUSIC_DIR="$HOME/music"
export XDG_VIDEOS_DIR="$HOME/videos"

# Now start sway! :)

exec dbus-launch --sh-syntax --exit-with-session sway 2>~/.sway.log
