#!/bin/sh

# alias stuff
alias poweroff="sudo /sbin/poweroff"

PS1="\$(pwd | sed -e 's/\/usr\/home\/'$USER'/~/' -e 's/\/home\/'$USER'/~/') $ "

# cleanup on exit
__cleanup() {
    rm -rf ~/.cache 2>/dev/null
    rm ~/.*hist* 2>/dev/null
    rm ~/.*wget* 2>/dev/null
    rm ~/.lesshst 2>/dev/null
    rm ~/.viminfo 2>/dev/null
    rmdir ~/* 2>/dev/null
    clear
}

trap __cleanup EXIT
