#!/bin/sh

# alias stuff
alias grep="grep --color=auto"
alias ls="ls -h --color=auto"
alias ip="ip -c"
alias ix="curl -F 'f:1=<-' ix.io"
alias poweroff="sudo /sbin/poweroff"
alias wget="wget --no-hsts"
# i once removed this having forgot how slow debian's site-lisp is -_-
alias emacs="emacs --no-site-lisp"

# FIXME: this will only work on linux systems
alias randstring="[ $(cat /proc/sys/kernel/random/entropy_avail) -gt 200 ] &&
                  tr -dc '[0-9A-Za-z~\!\@\#$%^&*()_+]' </dev/urandom | fold -w 25 | head -n 10 ||
                  printf \"WTF is wrong with your system?\n\""

# make startx use $XDG_CONFIG_HOME/x11/xsession
alias startx="startx $XDG_CONFIG_HOME/x11/xsession"

# FIXME: needs more testing!!
# setup a PS1 that *should* work in any POSIX compliant shell
PS1="$USER@${HOSTNAME:=$(hostname)}:\$(pwd | sed 's/\/home\/'$USER'/~/')\$(git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ [\1]/')\$(git status --short 2>/dev/null | sed 's/^ //g' | cut -d' ' -f1 | sort -u | tr -d '\n' | sed 's/\(.*\)/[\1]/')> "

# cleanup on exit
__cleanup() {
    rmdir ~/*
    rm ~/.*hist*
    rm ~/.lesshst
    rm ~/.viminfo
    clear
}

trap __cleanup EXIT
