#!/bin/sh
xrdb -load /etc/X11/xinit/xresources
systemctl --user restart redshift
systemctl --user restart dunst

if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval $(dbus-launch --exit-with-session --sh-syntax)
fi

systemctl --user import-environment

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment DISPLAY XAUTHORITY
fi

xmonad
