#!/bin/sh

export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_MUSIC_DIR="$HOME/Music"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_PUBLICSHARE_DIR="$HOME/Public"
export XDG_TEMPLATES_DIR="$XDG_DOCUMENTS_DIR/templates"
export XDG_VIDEOS_DIR="$HOME/Movies"

# ensure $XDG_*_DIRs exist
mkdir -p "$XDG_DESKTOP_DIR" \
    "$XDG_DOCUMENTS_DIR" \
    "$XDG_DOWNLOAD_DIR" \
    "$XDG_MUSIC_DIR" \
    "$XDG_PICTURES_DIR" \
    "$XDG_PUBLICSHARE_DIR" \
    "$XDG_TEMPLATES_DIR" \
    "$XDG_VIDEOS_DIR"
