[colors]
bright.black = "#595959"
bright.blue = "#79a8ff"
bright.cyan = "#6ae4b9"
bright.green = "#70b900"
bright.magenta = "#b6a0ff"
bright.red = "#ef8b50"
bright.white = "#ffffff"
bright.yellow = "#c0c530"

normal.black = "#000000"
normal.blue = "#2fafff"
normal.cyan = "#00d3d0"
normal.green = "#44bc44"
normal.magenta = "#feacd0"
normal.red = "#ff8059"
normal.white = "#bfbfbf"
normal.yellow = "#d0bc00"

primary.background = "#000000"
primary.foreground = "#ffffff"

[cursor]
blink_interval = 500
style.blinking = "Always"
style.shape = "Underline"

[font]
size = 14.5
