#!/bin/ksh

######################
## GENERAL SETTINGS ##
######################

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignorespace:ignoredups
HISTFILE="$HOME/.cache/ksh_history"
HISTSIZE=10000

# color dirs/files nicely
[ -f /usr/bin/dircolors ] && eval "$(dircolors)"

# load ksh-completeions
if [ -f "$HOME/.config/ksh/ksh-completion.sh" ]; then
	. "$HOME/.config/ksh/ksh-completion.sh"
fi

#################
## COOL PROMPT ##
#################

__git_branch() {
    BRANCH="$(git branch 2>/dev/null | grep '^*' | cut -d' ' -f2)"
    if [ "$BRANCH" != "" ]; then
        printf " $BRANCH"
    fi
}
__git_status() {
    if [ "$(__git_branch)" != "" ]; then
        if [ "$(git status --short 2>/dev/null)" != "" ]; then
            printf " ✗"
        fi
    fi
}

# universal prompt, should work anywhere
#PS1='\u@\h \w \$ '
# cool prompt with git repo status
PS1='\[\e[1m\]\[\e[38;5;249m\]\u@\h \[\e[38;5;202m\]\w\[\e[38;5;193m\]$(__git_branch)\[\e[31m\]$(__git_status) \[\e[38;5;15m\]\$ \[\e[0m\]'

###########################
## ALIAS ALL THE THINGS! ##
###########################

# alias stuff
alias ls="ls -h --color=auto"
alias grep="grep --color=auto"
alias wget="wget --hsts-file=/dev/null"
# i forgot how slow debians site-lisp is one time and removed this -_-
alias emacs="emacs --no-site-lisp"

# so uh, yeeaaaaah... see https://github.com/tmux/tmux/issues/142
# 😢
alias tmux='tmux -f $HOME/.config/tmux/tmux.conf'

# if on gentoo, make startx use $HOME/.xsession
if test $(uname -r | grep -i gentoo); then
    alias startx="startx $HOME/.xsession"
fi

#######################
## EXPORTS AND SHEEP ##
#######################

# cool gcc colors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# turn off these history files
export LESSHISTFILE='/dev/null'

# make libvte terminals happy
export GROFF_NO_SGR=1

#####################
## CUSTOM COMMANDS ##
#####################

# nice man colors
man() {
    env \
        LESS_TERMCAP_mb=$(printf "\e[1m\e[38;5;202m") \
        LESS_TERMCAP_md=$(printf "\e[1m\e[38;5;202m") \
        LESS_TERMCAP_me=$(printf "\e[0m") \
        LESS_TERMCAP_so=$(printf "\e[1m\e[38;5;201m") \
        LESS_TERMCAP_se=$(printf "\e[0m") \
        LESS_TERMCAP_us=$(printf "\e[1m\e[38;5;193m") \
        LESS_TERMCAP_ue=$(printf "\e[0m") \
        man "$@"
}

# this provides the main info i used htop for
htop() {
    free -h; echo; uptime; echo; ps au
}

# paste command
ix() {
    curl -F 'f:1=<-' ix.io
}

# if on gentoo, add gentoo-world-check, a @world file checker from:
# https://wiki.gentoo.org/wiki/World_file_(Portage)
# this can be helpfull for removing things from your @world file
if test $(uname -r | grep -i gentoo); then

    gentoo-world-check() {
        echo -n 'Are you sure you want to run gentoo-world-check? IT CAN TAKE SOME TIME!! (y/N)? '
        read answer
        if [ "$answer" != "${answer#[Yy]}" ]; then
            rm -i /tmp/deselect
            while read i ; do \
                if [ -n "$(qdepends -Q $i)" ]; then \
                    echo '' ; echo 'checking '$i ;
                    if [ -n "$(emerge -p --quiet --depclean $i)" ]; then \
                        echo $i' needs to stay in @world'
                    else
                        echo $i' can be deselected'
                        echo $i >> /tmp/deselect
                    fi
                fi
            done < /var/lib/portage/world
            echo '\n/tmp/deselect contains candidates for deselection'
            echo 'try: emerge --ask --deselect $(< /tmp/deselect)\n'
        fi
    }

fi

# cleanup on exit
__cleanup() {
    # don't run unless the login shell
    if [ "$-" == "ilms" ]; then
        rmdir ~/*
        rm ~/.*hist*
        rm ~/.lesshst
        rm ~/.viminfo
        rm -rf ~/.w3m
        clear
    fi
}

trap __cleanup EXIT
