vim.cmd.highlight('CursorLine guibg=NvimDarkGrey3')
vim.cmd.highlight('CursorLineNr guibg=NvimDarkGrey3')
vim.cmd.highlight('LineNr guifg=NvimLightGrey4')
vim.cmd.highlight('Normal guibg=black')
vim.cmd.highlight('NormalFloat guibg=NvimDarkGrey3')
vim.cmd.highlight('Operator guifg=#f99f99')
vim.cmd.highlight('Visual guibg=#260260')
