-- vim.cmd.highlight('CursorLine ctermbg=233 guibg=NvimDarkGrey3')
-- vim.cmd.highlight('CursorLineNr ctermbg=233 ctermfg=white cterm=bold guibg=NvimDarkGrey3')
-- vim.cmd.highlight('LineNr ctermfg=248 guifg=NvimLightGrey4')
-- vim.cmd.highlight('Normal ctermfg=white cterm=italic guibg=black')
-- vim.cmd.highlight('NormalFloat guibg=NvimDarkGrey3')
-- vim.cmd.highlight('Visual guibg=#260260')

-- 256 compatible colour scheme inspired by Xcode and Modus Vivendi
vim.cmd.colorscheme('lunaperche')

vim.cmd.highlight('StatusLine cterm=NONE ctermbg=233')
vim.cmd.highlight('StatusLineNc cterm=NONE ctermbg=0')
vim.cmd.highlight('VertSplit ctermbg=NONE')

vim.cmd.highlight('Normal ctermfg=white cterm=italic')
vim.cmd.highlight('Comment ctermfg=115 cterm=italic')
vim.cmd.highlight('Constant ctermfg=153 cterm=bold')
vim.cmd.highlight('Conditional ctermfg=209')
vim.cmd.highlight('PreProc ctermfg=209')
vim.cmd.highlight('Repeat ctermfg=209')
vim.cmd.highlight('Function ctermfg=183')
vim.cmd.highlight('Special ctermfg=183')
vim.cmd.highlight('Delimiter ctermfg=250')
vim.cmd.highlight('String ctermfg=111')
vim.cmd.highlight('Float ctermfg=153')
vim.cmd.highlight('Number ctermfg=153')
vim.cmd.highlight('Boolean ctermfg=183 cterm=italic')
vim.cmd.highlight('Type ctermfg=153')
vim.cmd.highlight('Keyword ctermfg=122 cterm=italic')
vim.cmd.highlight('Statement ctermfg=209')
vim.cmd.highlight('Todo ctermfg=216 cterm=italic,bold')
vim.cmd.highlight('MatchParen ctermfg=222 cterm=reverse')

vim.cmd.highlight('MoreMsg ctermfg=115')
vim.cmd.highlight('ModeMsg ctermfg=white cterm=bold')
vim.cmd.highlight('Directory ctermfg=153')
vim.cmd.highlight('PmenuSel ctermbg=24')
vim.cmd.highlight('FloatBorder ctermbg=234 ctermfg=238')

vim.cmd.highlight('CursorLine ctermbg=233')
vim.cmd.highlight('CursorLineNr ctermbg=233 ctermfg=white cterm=bold')
vim.cmd.highlight('LineNr ctermfg=248')
vim.cmd.highlight('EndOfBuffer ctermfg=248')

vim.cmd.highlight('PackerWorking ctermfg=248')
vim.cmd.highlight('clear PackerSuccess')
vim.cmd.highlight('link PackerSuccess DiffAdd')

vim.cmd.highlight('DiagnosticError ctermfg=203')
vim.cmd.highlight('DiagnosticHint ctermfg=115')
vim.cmd.highlight('DiagnosticInfo ctermfg=153')
vim.cmd.highlight('DiagnosticWarn ctermfg=222')
vim.cmd.highlight('ErrorMsg ctermbg=NONE ctermfg=203 cterm=NONE')
vim.cmd.highlight('WarningMsg ctermfg=222 cterm=NONE')
vim.cmd.highlight('Error ctermbg=NONE ctermfg=203 cterm=bold')

vim.cmd.highlight('Search ctermbg=24 ctermfg=231')
vim.cmd.highlight('IncSearch ctermbg=55 ctermfg=231')
vim.cmd.highlight('CurSearch ctermbg=55 ctermfg=231')

vim.cmd.highlight('DiffAdd ctermbg=NONE ctermfg=115')
vim.cmd.highlight('DiffChange ctermbg=NONE ctermfg=216')
vim.cmd.highlight('DiffDelete ctermbg=NONE ctermfg=203')
vim.cmd.highlight('diffLine ctermfg=white cterm=bold')
vim.cmd.highlight('diffSubname ctermfg=250 cterm=bold')

vim.cmd.highlight('clear diffAdded')
vim.cmd.highlight('clear diffChanged')
vim.cmd.highlight('clear diffFile')
vim.cmd.highlight('clear diffIndexLine')
vim.cmd.highlight('clear diffRemoved')

vim.cmd.highlight('link diffAdded DiffAdd')
vim.cmd.highlight('link diffChanged DiffChange')
vim.cmd.highlight('link diffFile Constant')
vim.cmd.highlight('link diffIndexLine Constant')
vim.cmd.highlight('link diffRemoved DiffDelete')
