vim.cmd.highlight('CursorLine ctermbg=233 guibg=NvimDarkGrey3')
vim.cmd.highlight('CursorLineNr ctermbg=233 ctermfg=white cterm=bold guibg=NvimDarkGrey3')
vim.cmd.highlight('LineNr ctermfg=248 guifg=NvimLightGrey4')
vim.cmd.highlight('Normal ctermfg=white cterm=italic guibg=black')
vim.cmd.highlight('NormalFloat guibg=NvimDarkGrey3')
vim.cmd.highlight('Visual guibg=#260260')
