theme = "cjb"

[editor]
cursorline = true
text-width = 72 # this should be the default for backwards compatibilty

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "underline"
